version: '3.1'
services:
  springboot:
    image: docker push siddarth71/docker-sid:tagname
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
